### ISSUE TITLE
Funk at Zoom 15 along Germany-Austria border

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter#31]
- Zoom 15 in EU on Germany-Austria border seriously funky (zoom 14- is fine) 😨
    - http://localhost:4000/#15/47.5846/13.0559
    - https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/15/17571/11446.png
    - ![11446](https://user-images.githubusercontent.com/853051/28352815-70fba798-6c0d-11e7-8c11-9daf99637825.png)

Following up from: https://github.com/mojodna/marblecutter/issues/17

Could be "fixed" with the smaller footprints being updated in https://github.com/mojodna/marblecutter/issues/28? Let's deploy #28 and then retest this New Zealand issue.

**Comment by nvkelso** [comment]
This is no longer an issue thanks to @mojodna's changes today :)

For future note: we do see an edge between sources and maybe an edge blending as mentioned in https://github.com/mojodna/marblecutter/issues/33#issuecomment-317135756 would fix that – but for another day.

**Comment by nvkelso** [comment]
The missing tile seems to be a server timeout issue / memory funk. We thing we fixed that but leaving this open until that's verified.

<img width="999" alt="screen shot 2017-07-21 at 17 09 23" src="https://user-images.githubusercontent.com/853051/28486534-67e9fade-6e37-11e7-85a2-dce5ad18d52d.png">

**Comment by mojodna** [comment]
It looks like it's still an error. Problematic tile: http://d34o1q5y1d9is8.cloudfront.net/hillshade/15/17573/11445.png

Likely partial stack trace:

```
...
File "/var/task/marblecutter/__init__.py", line 197, in read_window
int(buffer_pixels[0]):int(-buffer_pixels[0])]
IndexError: invalid index to scalar variable.
```

**Comment by mojodna** [comment]
Problematic tile now renders:

![image](https://user-images.githubusercontent.com/45/28583339-af5577c0-711d-11e7-9235-9e8a8e11698b.png)

@iandees will need to re-deploy Mapzen's tiler function to pick up the fix.

**Comment by iandees** [comment]
The Mapzen lambda tiler has been updated.

**Comment by iandees** [comment]
@nvkelso I think this is closeable, what do you think?

**Comment by nvkelso** [comment]
I'll have a look.

**Comment by nvkelso** [comment]
This looks better, but I'm still seeing artifacts of 2 types:

1. **True edge of data pixel buffer funk** (similar to what we've seen with other no-data zones along coastline), this is covered elsewhere in https://github.com/mojodna/marblecutter/issues/32.
2. The earlier **large buffer of no-data striping** this issue was filed for.

<img width="916" alt="screen shot 2017-07-25 at 11 11 41" src="https://user-images.githubusercontent.com/853051/28586897-1bcaeae6-712a-11e7-8591-b0c3b62727df.png">

For 1. above:

- https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/15/17571/11446.png
    - x-imagery-sources:austria/ogd-10m-at.tif, srtm/N47E013.tif
    - ![11446 1](https://user-images.githubusercontent.com/853051/28587000-76604d66-712a-11e7-9472-4125b5e40770.png)

For 2. above, which we need to debug now:

- https://k6yfeg1cx6.execute-api.us-east-1.amazonaws.com/Prod/normal/15/17572/11447.png?api_key=vector-tiles-VyYjZGS&
    - x-imagery-sources:austria/ogd-10m-at.tif **(note only a single source!)**
    - ![11447](https://user-images.githubusercontent.com/853051/28587055-a857e8a6-712a-11e7-9599-170657bba158.png)

**Comment by nvkelso** [comment]
@mojodna ☝️ and @iandees for 👀

**Comment by iandees** [comment]
Also seeing it at https://terrain-lambda.dev.mapzen.com/normal/14/4825/6161@2x.png, with source `ned13/USGS_NED_13_n41w074_IMG.tif`.

![image](https://user-images.githubusercontent.com/261584/28594341-9f43826a-715d-11e7-9d03-308ba0c1b36f.png)

**Comment by nvkelso** [comment]
Notably the 1x version of that resource **does not have the problem**!?

- https://terrain-lambda.dev.mapzen.com/normal/14/4825/6161.png

![](https://terrain-lambda.dev.mapzen.com/normal/14/4825/6161.png)

**Comment by mojodna** [comment]
Varietal 2 was fixed by considering the entire mask being used for interpolation rather than the eventual cropped area.

![iterm2 6hy45z](https://user-images.githubusercontent.com/45/28696261-5cf2da22-72e9-11e7-9021-dc88b6415951.png)

![iterm2 nbdxcm](https://user-images.githubusercontent.com/45/28696276-7024b89a-72e9-11e7-9aac-35c854e7688a.png)

**Comment by nvkelso** [comment]
Nice!

**Comment by mojodna** [comment]
Edge pixel funk improves when removing interpolation (at the cost of smoothness when overzooming). (This means that excessive edge pixel funk is a result of interpolation, particular at scale factors like 0.5.)

I started fiddling around with dilating / opening the mask (https://en.wikipedia.org/wiki/Mathematical_morphology) to achieve a similar buffering effect (numerically) as https://github.com/mojodna/marblecutter/issues/33#issuecomment-317137421 but haven't yet had any good results.

**Comment by nvkelso** [comment]
Wow, this looks fantastic! :cloud_with_lightning: 🗻

**Comment by iandees** [comment]
(This is deployed on the mapzen dev lambda tiler)

**Comment by nvkelso** [comment]
Verified we're down to a single pixel of funk on the edges, which makes the rest of this the same as #33 but this one has more details so closing #33.

**Comment by nvkelso** [comment]
This issue has been completed. 

(I filed https://github.com/mojodna/marblecutter/issues/45 to track future blurring work that's not needed for this release.)
